select * from order_detail;

-- NUMBER TRANSACTION SUCCEED IN EACH YEAR
-- 2021 = 1197; 2022 = 1234
SELECT EXTRACT(YEAR FROM ORDER_DATE), COUNT(ID)
FROM order_detail
WHERE IS_VALID = 1 AND IS_NET = 1
GROUP BY EXTRACT(YEAR FROM ORDER_DATE)

-- NUMBER OF TRANSACTION SUCCEED IN EACH YEAR IN EACH MONTH
-- IN 2021, THE MOST TRANSACTION OCCURRED IN AUGUST (184x) AND THE LEAST OCCURRED IN MARCH (30x)
-- IN 2022, THE MOST TRX OCCURRED IN JANUARY (178x) AND THE LEAST OCCURRED IN SEPT (40x)
SELECT
    EXTRACT(YEAR FROM ORDER_DATE) AS YEAR,
    EXTRACT(MONTH FROM ORDER_DATE) AS MONTH,
    COUNT(ID)
FROM order_detail
WHERE IS_VALID = 1 AND IS_NET = 1
    AND (EXTRACT(YEAR FROM ORDER_DATE)=2021 OR EXTRACT(YEAR FROM ORDER_DATE)=2022)
GROUP BY EXTRACT(YEAR FROM ORDER_DATE), EXTRACT(MONTH FROM ORDER_DATE)
ORDER BY  EXTRACT(YEAR FROM ORDER_DATE), COUNT(ID) DESC

-- THE AVERAGE TOTAL TRX SUCCEED IN EACH YEAR
-- 99.8 AVG TRX IN 2021; 102.8 AVG TRX IN 2022
-- >>> There has been an increase of product sales from 2021 to 2022 
SELECT TOTAL.ORDER_YR, ROUND(AVG(TOTAL.TOTAL_TRX), 1) AS AVERAGE_TOTAL_TRX
FROM (
    SELECT EXTRACT(YEAR FROM ORDER_DATE) AS ORDER_YR, EXTRACT(MONTH FROM ORDER_DATE) AS ORDER_MT, COUNT(ID) AS TOTAL_TRX
    FROM order_detail
    WHERE IS_VALID = 1 AND IS_NET = 1
        AND (EXTRACT(YEAR FROM ORDER_DATE)=2021 OR EXTRACT(YEAR FROM ORDER_DATE)=2022)
    GROUP BY EXTRACT(YEAR FROM ORDER_DATE), EXTRACT(MONTH FROM ORDER_DATE)
) TOTAL
GROUP BY TOTAL.ORDER_YR

-- TRANSACTION RECORDS EACH MONTH IN 2021
-- TRANSACTION WITH HIGHEST TOTAL TRX OCCURRED IN AUGUST (227.862.744) AND THE LOWEST OCCURRED IN APRIL (22.208.473)
SELECT EXTRACT(MONTH FROM ORDER_DATE), SUM(DISCOUNT_AFTER) FROM order_detail
WHERE IS_VALID = 1 AND IS_NET = 1
    AND EXTRACT(YEAR FROM ORDER_DATE)=2021
GROUP BY EXTRACT(MONTH FROM ORDER_DATE)
ORDER BY SUM(DISCOUNT_AFTER) DESC

-- TRANSACTION RECORDS EACH MONTH IN 2022
-- TRANSACTION WITH HIGHEST TOTAL TRX OCCURRED IN SEPT (559.290.228) AND THE LOWEST OCCURRED IN NOV (47.924.364)
SELECT EXTRACT(MONTH FROM ORDER_DATE), SUM(DISCOUNT_AFTER)
FROM order_detail
WHERE IS_VALID = 1 AND IS_NET = 1
    AND EXTRACT(YEAR FROM ORDER_DATE) = 2022
GROUP BY EXTRACT(MONTH FROM ORDER_DATE)
ORDER BY SUM(DISCOUNT_AFTER) DESC


-- TOTAL PRODUCT SOLD IN EACH YEAR
-- 2021: 2161 PRODUCTS HAS BEEN SOLD
-- 2022: 3558 PRODUCTS HAS BEEN SOLD
SELECT EXTRACT(YEAR FROM ORDER_DATE), SUM(QTY)
FROM order_detail
WHERE IS_NET=1 AND IS_VALID=1 
    AND (EXTRACT(YEAR FROM ORDER_DATE)=2021 OR EXTRACT(YEAR FROM ORDER_DATE)=2022)
GROUP BY EXTRACT(YEAR FROM ORDER_DATE)

-- TOTAL PRODUCT SOLD IN EACH YEAR IN EACH MONTH
-- IN 2021, MAX ACHIEVABLE PRODUCT SALES TOTAL OCCURRED IN OCT (459) AND THE LOWEST IN JAN (45)
-- IN 2022, MAX ACHIEVABLE PRODUCT SALES TOTAL OCCURRED IN SEPT (1072) AND THE LOWEST IN OCT (61)
SELECT EXTRACT(YEAR FROM ORDER_DATE), EXTRACT(MONTH FROM ORDER_DATE), SUM(QTY)
FROM order_detail
WHERE IS_NET=1 AND IS_VALID=1
    AND (EXTRACT(YEAR FROM ORDER_DATE)=2021 OR EXTRACT(YEAR FROM ORDER_DATE)=2022)
GROUP BY EXTRACT(YEAR FROM ORDER_DATE), EXTRACT(MONTH FROM ORDER_DATE)
ORDER BY EXTRACT(YEAR FROM ORDER_DATE), SUM(QTY) DESC

-- AVG OF PRODUCT SOLD IN EACH YEAR
-- IN 2021, AVG 180 PRODUCTS HAS SOLD, 2022: AVG 296 PRODUCTS HAS SOLD
SELECT TOTAL.ORDER_YR, ROUND(AVG(TOTAL.SUM),1)
FROM(
    SELECT EXTRACT(YEAR FROM ORDER_DATE) AS ORDER_YR, EXTRACT(MONTH FROM ORDER_DATE) AS ORDER_MT , SUM(QTY)
    FROM order_detail
    WHERE IS_NET=1 AND IS_VALID=1
        AND (EXTRACT(YEAR FROM ORDER_DATE)=2021 OR EXTRACT(YEAR FROM ORDER_DATE)=2022)
    GROUP BY EXTRACT(YEAR FROM ORDER_DATE), EXTRACT(MONTH FROM ORDER_DATE)
) TOTAL
GROUP BY TOTAL.ORDER_YR
